wgo:
  sqs:
    endpoint: null
    region: ${AWS_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
    observation-queue-name: ${OBSERVATION_QUEUE_NAME:observation-processing}
