ALTER TABLE events ADD COLUMN category VARCHAR(32) NOT NULL DEFAULT 'OTHER';
ALTER TABLE events ADD CONSTRAINT events_category_check
	CHECK (category IN ('TRANSPORT', 'WEATHER', 'COMMUNITY', 'FIRE', 'INFRASTRUCTURE', 'OTHER'));
